[package]
name = "poneglyph-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
derive_builder.workspace = true
oauth2.workspace = true
poneglyph.workspace = true
poneglyph-mcp.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower-http.workspace = true
tracing.workspace = true

[dev-dependencies]
reqwest.workspace = true
tempfile.workspace = true
