[package]
name = "poneglyph-mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
axum.workspace = true
async-trait.workspace = true
chrono.workspace = true
config.workspace = true
datafox.workspace = true
derive_builder.workspace = true
poneglyph-agent = { path = "../poneglyph-agent" }
poneglyph = { path = "../poneglyph"} 
rmcp.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
reqwest.workspace = true
tempfile.workspace = true
