/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as ConnectorsRouteRouteImport } from './routes/connectors/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectorsIndexRouteImport } from './routes/connectors/index'
import { Route as ConnectorsNewRouteImport } from './routes/connectors/new'
import { Route as ConnectorsAddRouteImport } from './routes/connectors/add'
import { Route as ConnectorsConnectorIdRouteRouteImport } from './routes/connectors/$connectorId/route'
import { Route as ConnectorsConnectorIdIndexRouteImport } from './routes/connectors/$connectorId/index'
import { Route as ConnectorsConnectorIdLogsRouteImport } from './routes/connectors/$connectorId/logs'
import { Route as ConnectorsGoogleOnboardRouteRouteImport } from './routes/connectors/google/onboard/route'
import { Route as ConnectorsGoogleOnboardIndexRouteImport } from './routes/connectors/google/onboard/index'
import { Route as ConnectorsGoogleOnboardSelectRouteImport } from './routes/connectors/google/onboard/select'
import { Route as ConnectorsGoogleOnboardDiscoverRouteImport } from './routes/connectors/google/onboard/discover'
import { Route as ConnectorsGoogleOnboardConnectRouteImport } from './routes/connectors/google/onboard/connect'

const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsRouteRoute = ConnectorsRouteRouteImport.update({
  id: '/connectors',
  path: '/connectors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectorsIndexRoute = ConnectorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConnectorsRouteRoute,
} as any)
const ConnectorsNewRoute = ConnectorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ConnectorsRouteRoute,
} as any)
const ConnectorsAddRoute = ConnectorsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => ConnectorsRouteRoute,
} as any)
const ConnectorsConnectorIdRouteRoute =
  ConnectorsConnectorIdRouteRouteImport.update({
    id: '/$connectorId',
    path: '/$connectorId',
    getParentRoute: () => ConnectorsRouteRoute,
  } as any)
const ConnectorsConnectorIdIndexRoute =
  ConnectorsConnectorIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnectorsConnectorIdRouteRoute,
  } as any)
const ConnectorsConnectorIdLogsRoute =
  ConnectorsConnectorIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => ConnectorsConnectorIdRouteRoute,
  } as any)
const ConnectorsGoogleOnboardRouteRoute =
  ConnectorsGoogleOnboardRouteRouteImport.update({
    id: '/google/onboard',
    path: '/google/onboard',
    getParentRoute: () => ConnectorsRouteRoute,
  } as any)
const ConnectorsGoogleOnboardIndexRoute =
  ConnectorsGoogleOnboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ConnectorsGoogleOnboardRouteRoute,
  } as any)
const ConnectorsGoogleOnboardSelectRoute =
  ConnectorsGoogleOnboardSelectRouteImport.update({
    id: '/select',
    path: '/select',
    getParentRoute: () => ConnectorsGoogleOnboardRouteRoute,
  } as any)
const ConnectorsGoogleOnboardDiscoverRoute =
  ConnectorsGoogleOnboardDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => ConnectorsGoogleOnboardRouteRoute,
  } as any)
const ConnectorsGoogleOnboardConnectRoute =
  ConnectorsGoogleOnboardConnectRouteImport.update({
    id: '/connect',
    path: '/connect',
    getParentRoute: () => ConnectorsGoogleOnboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRouteRouteWithChildren
  '/entities': typeof EntitiesRoute
  '/connectors/$connectorId': typeof ConnectorsConnectorIdRouteRouteWithChildren
  '/connectors/add': typeof ConnectorsAddRoute
  '/connectors/new': typeof ConnectorsNewRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/connectors/google/onboard': typeof ConnectorsGoogleOnboardRouteRouteWithChildren
  '/connectors/$connectorId/logs': typeof ConnectorsConnectorIdLogsRoute
  '/connectors/$connectorId/': typeof ConnectorsConnectorIdIndexRoute
  '/connectors/google/onboard/connect': typeof ConnectorsGoogleOnboardConnectRoute
  '/connectors/google/onboard/discover': typeof ConnectorsGoogleOnboardDiscoverRoute
  '/connectors/google/onboard/select': typeof ConnectorsGoogleOnboardSelectRoute
  '/connectors/google/onboard/': typeof ConnectorsGoogleOnboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entities': typeof EntitiesRoute
  '/connectors/add': typeof ConnectorsAddRoute
  '/connectors/new': typeof ConnectorsNewRoute
  '/connectors': typeof ConnectorsIndexRoute
  '/connectors/$connectorId/logs': typeof ConnectorsConnectorIdLogsRoute
  '/connectors/$connectorId': typeof ConnectorsConnectorIdIndexRoute
  '/connectors/google/onboard/connect': typeof ConnectorsGoogleOnboardConnectRoute
  '/connectors/google/onboard/discover': typeof ConnectorsGoogleOnboardDiscoverRoute
  '/connectors/google/onboard/select': typeof ConnectorsGoogleOnboardSelectRoute
  '/connectors/google/onboard': typeof ConnectorsGoogleOnboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connectors': typeof ConnectorsRouteRouteWithChildren
  '/entities': typeof EntitiesRoute
  '/connectors/$connectorId': typeof ConnectorsConnectorIdRouteRouteWithChildren
  '/connectors/add': typeof ConnectorsAddRoute
  '/connectors/new': typeof ConnectorsNewRoute
  '/connectors/': typeof ConnectorsIndexRoute
  '/connectors/google/onboard': typeof ConnectorsGoogleOnboardRouteRouteWithChildren
  '/connectors/$connectorId/logs': typeof ConnectorsConnectorIdLogsRoute
  '/connectors/$connectorId/': typeof ConnectorsConnectorIdIndexRoute
  '/connectors/google/onboard/connect': typeof ConnectorsGoogleOnboardConnectRoute
  '/connectors/google/onboard/discover': typeof ConnectorsGoogleOnboardDiscoverRoute
  '/connectors/google/onboard/select': typeof ConnectorsGoogleOnboardSelectRoute
  '/connectors/google/onboard/': typeof ConnectorsGoogleOnboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connectors'
    | '/entities'
    | '/connectors/$connectorId'
    | '/connectors/add'
    | '/connectors/new'
    | '/connectors/'
    | '/connectors/google/onboard'
    | '/connectors/$connectorId/logs'
    | '/connectors/$connectorId/'
    | '/connectors/google/onboard/connect'
    | '/connectors/google/onboard/discover'
    | '/connectors/google/onboard/select'
    | '/connectors/google/onboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entities'
    | '/connectors/add'
    | '/connectors/new'
    | '/connectors'
    | '/connectors/$connectorId/logs'
    | '/connectors/$connectorId'
    | '/connectors/google/onboard/connect'
    | '/connectors/google/onboard/discover'
    | '/connectors/google/onboard/select'
    | '/connectors/google/onboard'
  id:
    | '__root__'
    | '/'
    | '/connectors'
    | '/entities'
    | '/connectors/$connectorId'
    | '/connectors/add'
    | '/connectors/new'
    | '/connectors/'
    | '/connectors/google/onboard'
    | '/connectors/$connectorId/logs'
    | '/connectors/$connectorId/'
    | '/connectors/google/onboard/connect'
    | '/connectors/google/onboard/discover'
    | '/connectors/google/onboard/select'
    | '/connectors/google/onboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectorsRouteRoute: typeof ConnectorsRouteRouteWithChildren
  EntitiesRoute: typeof EntitiesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors': {
      id: '/connectors'
      path: '/connectors'
      fullPath: '/connectors'
      preLoaderRoute: typeof ConnectorsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connectors/': {
      id: '/connectors/'
      path: '/'
      fullPath: '/connectors/'
      preLoaderRoute: typeof ConnectorsIndexRouteImport
      parentRoute: typeof ConnectorsRouteRoute
    }
    '/connectors/new': {
      id: '/connectors/new'
      path: '/new'
      fullPath: '/connectors/new'
      preLoaderRoute: typeof ConnectorsNewRouteImport
      parentRoute: typeof ConnectorsRouteRoute
    }
    '/connectors/add': {
      id: '/connectors/add'
      path: '/add'
      fullPath: '/connectors/add'
      preLoaderRoute: typeof ConnectorsAddRouteImport
      parentRoute: typeof ConnectorsRouteRoute
    }
    '/connectors/$connectorId': {
      id: '/connectors/$connectorId'
      path: '/$connectorId'
      fullPath: '/connectors/$connectorId'
      preLoaderRoute: typeof ConnectorsConnectorIdRouteRouteImport
      parentRoute: typeof ConnectorsRouteRoute
    }
    '/connectors/$connectorId/': {
      id: '/connectors/$connectorId/'
      path: '/'
      fullPath: '/connectors/$connectorId/'
      preLoaderRoute: typeof ConnectorsConnectorIdIndexRouteImport
      parentRoute: typeof ConnectorsConnectorIdRouteRoute
    }
    '/connectors/$connectorId/logs': {
      id: '/connectors/$connectorId/logs'
      path: '/logs'
      fullPath: '/connectors/$connectorId/logs'
      preLoaderRoute: typeof ConnectorsConnectorIdLogsRouteImport
      parentRoute: typeof ConnectorsConnectorIdRouteRoute
    }
    '/connectors/google/onboard': {
      id: '/connectors/google/onboard'
      path: '/google/onboard'
      fullPath: '/connectors/google/onboard'
      preLoaderRoute: typeof ConnectorsGoogleOnboardRouteRouteImport
      parentRoute: typeof ConnectorsRouteRoute
    }
    '/connectors/google/onboard/': {
      id: '/connectors/google/onboard/'
      path: '/'
      fullPath: '/connectors/google/onboard/'
      preLoaderRoute: typeof ConnectorsGoogleOnboardIndexRouteImport
      parentRoute: typeof ConnectorsGoogleOnboardRouteRoute
    }
    '/connectors/google/onboard/select': {
      id: '/connectors/google/onboard/select'
      path: '/select'
      fullPath: '/connectors/google/onboard/select'
      preLoaderRoute: typeof ConnectorsGoogleOnboardSelectRouteImport
      parentRoute: typeof ConnectorsGoogleOnboardRouteRoute
    }
    '/connectors/google/onboard/discover': {
      id: '/connectors/google/onboard/discover'
      path: '/discover'
      fullPath: '/connectors/google/onboard/discover'
      preLoaderRoute: typeof ConnectorsGoogleOnboardDiscoverRouteImport
      parentRoute: typeof ConnectorsGoogleOnboardRouteRoute
    }
    '/connectors/google/onboard/connect': {
      id: '/connectors/google/onboard/connect'
      path: '/connect'
      fullPath: '/connectors/google/onboard/connect'
      preLoaderRoute: typeof ConnectorsGoogleOnboardConnectRouteImport
      parentRoute: typeof ConnectorsGoogleOnboardRouteRoute
    }
  }
}

interface ConnectorsConnectorIdRouteRouteChildren {
  ConnectorsConnectorIdLogsRoute: typeof ConnectorsConnectorIdLogsRoute
  ConnectorsConnectorIdIndexRoute: typeof ConnectorsConnectorIdIndexRoute
}

const ConnectorsConnectorIdRouteRouteChildren: ConnectorsConnectorIdRouteRouteChildren =
  {
    ConnectorsConnectorIdLogsRoute: ConnectorsConnectorIdLogsRoute,
    ConnectorsConnectorIdIndexRoute: ConnectorsConnectorIdIndexRoute,
  }

const ConnectorsConnectorIdRouteRouteWithChildren =
  ConnectorsConnectorIdRouteRoute._addFileChildren(
    ConnectorsConnectorIdRouteRouteChildren,
  )

interface ConnectorsGoogleOnboardRouteRouteChildren {
  ConnectorsGoogleOnboardConnectRoute: typeof ConnectorsGoogleOnboardConnectRoute
  ConnectorsGoogleOnboardDiscoverRoute: typeof ConnectorsGoogleOnboardDiscoverRoute
  ConnectorsGoogleOnboardSelectRoute: typeof ConnectorsGoogleOnboardSelectRoute
  ConnectorsGoogleOnboardIndexRoute: typeof ConnectorsGoogleOnboardIndexRoute
}

const ConnectorsGoogleOnboardRouteRouteChildren: ConnectorsGoogleOnboardRouteRouteChildren =
  {
    ConnectorsGoogleOnboardConnectRoute: ConnectorsGoogleOnboardConnectRoute,
    ConnectorsGoogleOnboardDiscoverRoute: ConnectorsGoogleOnboardDiscoverRoute,
    ConnectorsGoogleOnboardSelectRoute: ConnectorsGoogleOnboardSelectRoute,
    ConnectorsGoogleOnboardIndexRoute: ConnectorsGoogleOnboardIndexRoute,
  }

const ConnectorsGoogleOnboardRouteRouteWithChildren =
  ConnectorsGoogleOnboardRouteRoute._addFileChildren(
    ConnectorsGoogleOnboardRouteRouteChildren,
  )

interface ConnectorsRouteRouteChildren {
  ConnectorsConnectorIdRouteRoute: typeof ConnectorsConnectorIdRouteRouteWithChildren
  ConnectorsAddRoute: typeof ConnectorsAddRoute
  ConnectorsNewRoute: typeof ConnectorsNewRoute
  ConnectorsIndexRoute: typeof ConnectorsIndexRoute
  ConnectorsGoogleOnboardRouteRoute: typeof ConnectorsGoogleOnboardRouteRouteWithChildren
}

const ConnectorsRouteRouteChildren: ConnectorsRouteRouteChildren = {
  ConnectorsConnectorIdRouteRoute: ConnectorsConnectorIdRouteRouteWithChildren,
  ConnectorsAddRoute: ConnectorsAddRoute,
  ConnectorsNewRoute: ConnectorsNewRoute,
  ConnectorsIndexRoute: ConnectorsIndexRoute,
  ConnectorsGoogleOnboardRouteRoute:
    ConnectorsGoogleOnboardRouteRouteWithChildren,
}

const ConnectorsRouteRouteWithChildren = ConnectorsRouteRoute._addFileChildren(
  ConnectorsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectorsRouteRoute: ConnectorsRouteRouteWithChildren,
  EntitiesRoute: EntitiesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
