[package]
name = "poneglyph-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
clap.workspace = true
config.workspace = true
derive_builder.workspace = true
dotenvy.workspace = true
poneglyph-core = { path = "../poneglyph-core" }
poneglyph-api = { path = "../poneglyph-api" }
poneglyph-db = { path = "../poneglyph-db" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
toml.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true

[[bin]]
name = "poneglyph"
path = "src/main.rs"

[dev-dependencies]
tempfile.workspace = true
