[package]
name = "poneglyph-agent"
version = "0.1.0"
edition = "2024"

[dependencies]
agents.workspace = true
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
datafox.workspace = true
evals.workspace = true
poneglyph = { path = "../poneglyph" }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio.workspace = true

[build-dependencies]
anyhow.workspace = true
evals.workspace = true
